name:                minesweeper
version:             0.1.0.0
github:              "jarota/minesweeper"
license:             BSD3
author:              "jarota"
maintainer:          "example@example.com"
copyright:           "2019 jarota"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/minesweeper#readme>

dependencies:
- base >= 4.7 && < 5
- random
- scotty
- blaze-html
- aeson
- bytestring
- wai-middleware-static
- wai-extra

library:
  source-dirs: src

executables:
  minesweeper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minesweeper

tests:
  minesweeper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minesweeper
